import { useState, useEffect, useCallback } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { suppliersApi } from '../../../suppliersApi';

// Helper to split full name if editing an individual
const parseFullName = (fullName = '') => {
  const parts = fullName.trim().split(' ');
  return {
    firstName: parts[0] || '',
    middleName: parts[1] || '',
    lastName: parts.slice(2).join(' ') || '',
  };
};

export function useSupplierForm() {
  const navigate = useNavigate();
  const { id } = useParams();
  const isEditing = Boolean(id);

  const [loading, setLoading] = useState(isEditing);
  const [submitting, setSubmitting] = useState(false);

  const [formData, setFormData] = useState({
    supplierType: 'ORGANIZATION', // 'ORGANIZATION' | 'INDIVIDUAL'
    supplierCode: 'Auto-generated by System (SUP-XXXX)',
    // Organization fields
    name: '',
    companyName: '',
    contactPerson: '',
    // Individual Person detailed fields
    firstName: '',
    middleName: '',
    lastName: '',
    nationalId: '',
    altPhone: '',
    // Shared fields
    email: '',
    phone: '',
    tin: '',
    address: '',
    city: '',
    region: '',
    bankName: '',
    accountNumber: '',
    paymentTerms: 'Net 30',
    status: 'ACTIVE',
    // Dynamic Additional / Alternate Contacts
    additionalContacts: [],
    // Dynamic Multiple Payout Channels / Accounts
    payoutChannels: [
      {
        channelType: 'BANK',
        bankName: 'Commercial Bank of Ethiopia (CBE)',
        accountNumber: '',
        accountName: '',
        isPrimary: true,
      },
    ],
  });

  // Load existing supplier if editing
  const loadSupplier = useCallback(async () => {
    if (!isEditing || !id) return;
    try {
      setLoading(true);
      const res = await suppliersApi.getSupplierById(id);
      const s = res?.data;
      if (s) {
        const isIndividual = s.supplierType === 'INDIVIDUAL' || Boolean(s.person);
        const nameParts = parseFullName(
          s.name || s.person?.firstName
            ? `${s.person?.firstName || ''} ${s.person?.middleName || ''} ${s.person?.lastName || ''}`
            : ''
        );

        let existingChannels = s.payoutChannels || s.paymentChannels || s.paymentMethods || [];
        if (!Array.isArray(existingChannels) || existingChannels.length === 0) {
          existingChannels = [
            {
              channelType: 'BANK',
              bankName: s.bankName || 'Commercial Bank of Ethiopia (CBE)',
              accountNumber: s.accountNumber || '',
              accountName: s.name || '',
              isPrimary: true,
            },
          ];
        }

        setFormData({
          supplierType: isIndividual ? 'INDIVIDUAL' : 'ORGANIZATION',
          supplierCode: s.supplierCode || '',
          name: s.name || '',
          companyName: s.companyName || s.name || '',
          contactPerson: s.contactPerson || '',
          firstName: s.person?.firstName || nameParts.firstName,
          middleName: s.person?.middleName || nameParts.middleName,
          lastName: s.person?.lastName || nameParts.lastName,
          nationalId: s.nationalId || s.person?.nationalId || '',
          altPhone: s.altPhone || '',
          email: s.email || s.person?.email || '',
          phone: s.phone || s.person?.phone || '',
          tin: s.tin || '',
          address: s.address || '',
          city: s.city || '',
          region: s.region || '',
          bankName: s.bankName || '',
          accountNumber: s.accountNumber || '',
          paymentTerms: s.paymentTerms || 'Net 30',
          status: s.status || 'ACTIVE',
          additionalContacts: s.additionalContacts || s.contacts || [],
          payoutChannels: existingChannels,
        });
      }
    } catch (err) {
      console.error('Failed to load supplier for edit:', err);
      toast.error('Failed to load supplier details');
    } finally {
      setLoading(false);
    }
  }, [id, isEditing]);

  useEffect(() => {
    loadSupplier();
  }, [loadSupplier]);

  // Sync full name when individual name fields change
  const handleIndividualNameChange = (field, value) => {
    setFormData((prev) => {
      const updated = { ...prev, [field]: value };
      const fullName = `${updated.firstName} ${updated.middleName} ${updated.lastName}`
        .replace(/\s+/g, ' ')
        .trim();
      return {
        ...updated,
        name: fullName,
        contactPerson: fullName,
      };
    });
  };

  // Dynamic Contact Person Management
  const handleAddContact = () => {
    setFormData((prev) => ({
      ...prev,
      additionalContacts: [
        ...prev.additionalContacts,
        { name: '', role: 'Logistics / Sales Representative', phone: '', email: '' },
      ],
    }));
  };

  const handleRemoveContact = (index) => {
    setFormData((prev) => ({
      ...prev,
      additionalContacts: prev.additionalContacts.filter((_, i) => i !== index),
    }));
  };

  const handleUpdateContact = (index, field, value) => {
    setFormData((prev) => {
      const updated = [...prev.additionalContacts];
      updated[index] = { ...updated[index], [field]: value };
      return { ...prev, additionalContacts: updated };
    });
  };

  // Dynamic Multiple Payout Channels Management
  const handleAddPayoutChannel = () => {
    setFormData((prev) => ({
      ...prev,
      payoutChannels: [
        ...prev.payoutChannels,
        {
          channelType: 'BANK',
          bankName: 'Awash Bank',
          accountNumber: '',
          accountName: prev.name || '',
          isPrimary: false,
        },
      ],
    }));
  };

  const handleRemovePayoutChannel = (index) => {
    setFormData((prev) => ({
      ...prev,
      payoutChannels: prev.payoutChannels.filter((_, i) => i !== index),
    }));
  };

  const handleUpdatePayoutChannel = (index, field, value) => {
    setFormData((prev) => {
      const updated = [...prev.payoutChannels];
      updated[index] = { ...updated[index], [field]: value };
      if (field === 'isPrimary' && value === true) {
        updated.forEach((ch, i) => {
          if (i !== index) ch.isPrimary = false;
        });
      }
      return { ...prev, payoutChannels: updated };
    });
  };

  const handleSubmit = async (e) => {
    if (e && e.preventDefault) e.preventDefault();

    let computedName = formData.name;
    if (formData.supplierType === 'INDIVIDUAL') {
      computedName = `${formData.firstName} ${formData.middleName} ${formData.lastName}`
        .replace(/\s+/g, ' ')
        .trim();
      if (!formData.firstName.trim()) {
        toast.error('First name is required for individual supplier');
        return;
      }
    } else {
      if (!formData.name.trim()) {
        toast.error('Company / Supplier name is required');
        return;
      }
    }

    try {
      setSubmitting(true);
      const primaryChannel =
        formData.payoutChannels.find((ch) => ch.isPrimary) || formData.payoutChannels[0];

      const payload = {
        ...formData,
        bankName: primaryChannel?.bankName || formData.bankName,
        accountNumber: primaryChannel?.accountNumber || formData.accountNumber,
        name: computedName,
        contactPerson:
          formData.supplierType === 'INDIVIDUAL' ? computedName : formData.contactPerson,
        person:
          formData.supplierType === 'INDIVIDUAL'
            ? {
                firstName: formData.firstName,
                middleName: formData.middleName,
                lastName: formData.lastName,
                phone: formData.phone,
                email: formData.email,
                nationalId: formData.nationalId,
              }
            : null,
      };

      if (isEditing) {
        await suppliersApi.updateSupplier(id, payload);
        toast.success('Supplier updated successfully');
      } else {
        await suppliersApi.createSupplier(payload);
        toast.success('New Supplier registered successfully');
      }
      navigate('/suppliers');
    } catch (err) {
      console.error('Error saving supplier:', err);
      toast.error(err.response?.data?.message || err.message || 'Failed to save supplier details');
    } finally {
      setSubmitting(false);
    }
  };

  return {
    id,
    isEditing,
    loading,
    submitting,
    formData,
    setFormData,
    handleIndividualNameChange,
    handleAddContact,
    handleRemoveContact,
    handleUpdateContact,
    handleAddPayoutChannel,
    handleRemovePayoutChannel,
    handleUpdatePayoutChannel,
    handleSubmit,
  };
}
